[[fastlowess]]
arch = "aarch64"
git-tree-sha1 = "8223ebc567da11a0d1036eaf43fafd0e1ba38bdf"
os = "macos"

    [[fastlowess.download]]
    sha256 = "3d8659a1d6e0d3edd30a25ad642b767e63112632657f389838d408c0e4116f55"
    url = "https://github.com/JuliaBinaryWrappers/fastlowess_jll.jl/releases/download/fastlowess-v4.0.0+0/fastlowess.v4.0.0.aarch64-apple-darwin.tar.gz"
[[fastlowess]]
arch = "aarch64"
git-tree-sha1 = "8f886458c2863fd1dce8546c78d9ff82f66391c8"
libc = "glibc"
os = "linux"

    [[fastlowess.download]]
    sha256 = "b02135362d3f2eaef6528f7e7f5dde6337247f4fd3a4ea86d7770110f1d10f52"
    url = "https://github.com/JuliaBinaryWrappers/fastlowess_jll.jl/releases/download/fastlowess-v4.0.0+0/fastlowess.v4.0.0.aarch64-linux-gnu.tar.gz"
[[fastlowess]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "e74bf4a090654150a559f63ee928bbe4ff1eee6b"
libc = "glibc"
os = "linux"

    [[fastlowess.download]]
    sha256 = "fec0dc23a3c674f37f9d09c93de85e52e9940fd5bb92b4a390cf09fb0278c64d"
    url = "https://github.com/JuliaBinaryWrappers/fastlowess_jll.jl/releases/download/fastlowess-v4.0.0+0/fastlowess.v4.0.0.armv6l-linux-gnueabihf.tar.gz"
[[fastlowess]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "54cbfbc306b819808b2ba8c3f0dd140b3e2f7189"
libc = "glibc"
os = "linux"

    [[fastlowess.download]]
    sha256 = "5c6de881d778bec6b816845902642803feb7d351be8a5fd7f6dd698f77a69ca2"
    url = "https://github.com/JuliaBinaryWrappers/fastlowess_jll.jl/releases/download/fastlowess-v4.0.0+0/fastlowess.v4.0.0.armv7l-linux-gnueabihf.tar.gz"
[[fastlowess]]
arch = "i686"
git-tree-sha1 = "904883a980627e5fa4f1f49560663e04976c8e3b"
libc = "glibc"
os = "linux"

    [[fastlowess.download]]
    sha256 = "46a2b0dbba511f3d605f45d01fe9430afbf41444b329313c004bdd4542d4a9b8"
    url = "https://github.com/JuliaBinaryWrappers/fastlowess_jll.jl/releases/download/fastlowess-v4.0.0+0/fastlowess.v4.0.0.i686-linux-gnu.tar.gz"
[[fastlowess]]
arch = "powerpc64le"
git-tree-sha1 = "d268d713b0ded92ebd90b8c71d7e7d6a4463f54e"
libc = "glibc"
os = "linux"

    [[fastlowess.download]]
    sha256 = "e2e856d0477065c41e5a3e6995723fae1be6cf3b33627c6e2c9ecc863005934e"
    url = "https://github.com/JuliaBinaryWrappers/fastlowess_jll.jl/releases/download/fastlowess-v4.0.0+0/fastlowess.v4.0.0.powerpc64le-linux-gnu.tar.gz"
[[fastlowess]]
arch = "x86_64"
git-tree-sha1 = "536269dabfa326519bde78aeb843aacba81ee284"
os = "macos"

    [[fastlowess.download]]
    sha256 = "ffef0a87d6e9d9cc45fcbb30af83775fd4c7f7a44222d6c3383ac5e9449a9303"
    url = "https://github.com/JuliaBinaryWrappers/fastlowess_jll.jl/releases/download/fastlowess-v4.0.0+0/fastlowess.v4.0.0.x86_64-apple-darwin.tar.gz"
[[fastlowess]]
arch = "x86_64"
git-tree-sha1 = "981aae716b440d8e3ad7733d355a36d7d1e4cb95"
libc = "glibc"
os = "linux"

    [[fastlowess.download]]
    sha256 = "abb769418ba733e339bdfd903d57a8ffe3a8022ab0f8aaf6d334a0cc23339a22"
    url = "https://github.com/JuliaBinaryWrappers/fastlowess_jll.jl/releases/download/fastlowess-v4.0.0+0/fastlowess.v4.0.0.x86_64-linux-gnu.tar.gz"
[[fastlowess]]
arch = "x86_64"
git-tree-sha1 = "5faf84544b7940a9e7b282fd06d81d763c9f57ec"
os = "windows"

    [[fastlowess.download]]
    sha256 = "23e07732178db63e764c70e949a0a49aff874a38ea123b720e78402601cc38a3"
    url = "https://github.com/JuliaBinaryWrappers/fastlowess_jll.jl/releases/download/fastlowess-v4.0.0+0/fastlowess.v4.0.0.x86_64-w64-mingw32.tar.gz"
