# Autogenerated wrapper script for fastlowess_jll for armv6l-linux-gnueabihf
export libfastlowess_jl

JLLWrappers.@generate_wrapper_header("fastlowess")
JLLWrappers.@declare_library_product(libfastlowess_jl, "libfastlowess_jl.so")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libfastlowess_jl,
        "lib/libfastlowess_jl.so",
        nothing,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
