# Autogenerated wrapper script for fastlowess_jll for x86_64-w64-mingw32
export libfastlowess_jl

JLLWrappers.@generate_wrapper_header("fastlowess")
JLLWrappers.@declare_library_product(libfastlowess_jl, "fastlowess_jl.dll")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libfastlowess_jl,
        "bin\\fastlowess_jl.dll",
        nothing,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
